name: CI/CD

on:
  push:
    branches:
      - '*'  # Trigger on push events for all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint  # Adjust the lint command as needed

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test  # Adjust the test command as needed

  deploy:
    runs-on: ubuntu-latest
    needs: [test]  # Ensure that 'deploy' job runs only after 'test' job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      # Add additional steps for deployment here, such as deploying to a hosting platform
