name: CI/CD

on:
  push:
    branches:
      - "*" # Trigger on push events for all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint # Adjust the lint command as needed

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test # Adjust the test command as needed

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: /coverage-xml/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: true
          hide_complexity: true
          indicators: true
          output: file

  build:
    name: Build
    runs-on: ubuntu-latest
    # needs: [lint, test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Archive production files
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
